services:
  web:
    build:
      command: "npm install && npm build"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORTA_DA_APLICACAO
        value: 3000:3000
      - key: PORTA_PRISMA
        value: 3306:3306
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        value: pk_test_c2FmZS1pbXAtNDAuY2xlcmsuYWNjb3VudHMuZGV2JA
      - key: CLERK_SECRET_KEY
        value: sk_test_kX80b2w5H1ecmvM5JAyeUwXxezyCzeRaHxxuH2CDzA
      - key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
        value: /sign-in
      - key: NEXT_PUBLIC_CLERK_SIGN_UP_URL
        value: /sign-up
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
        value: /dashboard
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
        value: /dashboard
      - key: OPENAI_API_KEY
        value: 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
      - key: REPLICATE_API_TOKEN
        value: r8_V4MaN8voZBK8IO2seIxbobvBQHkGext3UW3up
      - key: DATABASE_URL
        value: 'mysql://nhn2pv7e1nfd5hs0h0d0:pscale_pw_XFrXjGuSMQTB1m2LPVLmWZIm1rvvrqKn1OaDzCd6jkk@aws.connect.psdb.cloud/ai-saas?sslaccept=strict'
      - key: KEY_STRIPE_PUBLIC
        value: pk_test_51NwsOdLctoyjSc8PGvCTzU0Rs3d6o1numF2ePtuY2V3BOJzE4VQRngRgLTGPPI77q7UaUx0hDZtWSqJOefBPfdaL008LNTJHWT
      - key: KEY_STRIPE_SECRET
        value: sk_test_51NwsOdLctoyjSc8Pd0mXtHwhAEORTXfAV2iZAUqmcx1sAE7DFU9N8D1FH68Xv2ElnqTUCa6rgOqZoXwl2qrAMs9A00PYepwRrI
      - key: NEXT_PUBLIC_APP_URL
        value: http://localhost:3000
      - key: STRIPE_WEBHOOK_SECRET
        value: whsec_efde9a4e209c999cd52440618b1c62e228f2a42e78beb4f4acc25949ec2bdb61
    startCommand: "npm start"
    healthCheckPath: "/"

databases:
  main:
    name: "db"